use memmap2::Mmap;
use std::fs::File;
use std::path::Path;
use regex::bytes::Regex;
use base64::Engine;

use crate::db::GCodeMetadata;

pub fn analyze_gcode(path: &Path) -> Result<GCodeMetadata, std::io::Error> {
    let file = File::open(path)?;
    let mmap = unsafe { Mmap::map(&file)? };
    
    let len = mmap.len();
    let head_len = std::cmp::min(len, 65536);
    let tail_len = std::cmp::min(len - head_len, 65536);
    
    let head = &mmap[..head_len];
    let tail = if tail_len > 0 {
        &mmap[len - tail_len..]
    } else {
        &[]
    };

    let mut scan_bytes = Vec::with_capacity(head_len + tail_len);
    scan_bytes.extend_from_slice(head);
    scan_bytes.extend_from_slice(tail);

    let mut estimated_time = None;
    let mut layer_height = None;
    let mut slicer_type = None;
    let mut thumbnail_path = None;

    // 1. Generator check
    let re_generator = Regex::new(r"(?i);\s*(?:generator|GENERATOR)\s*=\s*([^\r\n]+)|;\s*GENERATOR:\s*([^\r\n]+)").unwrap();
    if let Some(caps) = re_generator.captures(&scan_bytes) {
        let gen = caps.get(1).or_else(|| caps.get(2))
            .map(|m| String::from_utf8_lossy(m.as_bytes()).trim().to_string());
        slicer_type = gen;
    }

    // 2. Layer height check
    let re_layer = Regex::new(r"(?i);\s*(?:layer_height|Layer height)\s*[:=]\s*([0-9.]+)").unwrap();
    if let Some(caps) = re_layer.captures(&scan_bytes) {
        if let Some(m) = caps.get(1) {
            if let Ok(h) = String::from_utf8_lossy(m.as_bytes()).parse::<f64>() {
                layer_height = Some(h);
            }
        }
    }

    // 3. Estimated print time check
    let re_time_secs = Regex::new(r"(?i);\s*(?:TIME|estimated_time)\s*[:=]\s*([0-9.]+)").unwrap();
    if let Some(caps) = re_time_secs.captures(&scan_bytes) {
        if let Some(m) = caps.get(1) {
            if let Ok(t) = String::from_utf8_lossy(m.as_bytes()).parse::<f64>() {
                estimated_time = Some(t);
            }
        }
    }

    if estimated_time.is_none() {
        let re_time_hms = Regex::new(r"(?i);\s*estimated printing time\s*[^=\r\n]*=\s*(?:(\d+)h\s*)?(?:(\d+)m\s*)?(?:(\d+)s)?").unwrap();
        if let Some(caps) = re_time_hms.captures(&scan_bytes) {
            let mut total_secs = 0.0;
            let h: f64 = caps.get(1).and_then(|m| String::from_utf8_lossy(m.as_bytes()).parse().ok()).unwrap_or(0.0);
            let m: f64 = caps.get(2).and_then(|m| String::from_utf8_lossy(m.as_bytes()).parse().ok()).unwrap_or(0.0);
            let s: f64 = caps.get(3).and_then(|m| String::from_utf8_lossy(m.as_bytes()).parse().ok()).unwrap_or(0.0);
            total_secs += h * 3600.0 + m * 60.0 + s;
            if total_secs > 0.0 {
                estimated_time = Some(total_secs);
            }
        }
    }

    // 4. Thumbnail check & extraction
    let re_thumb = Regex::new(r"(?s);\s*thumbnail\s+begin\s+(\d+x\d+)\s+(\d+)\r?\n(.*?);\s*thumbnail\s+end").unwrap();
    if let Some(caps) = re_thumb.captures(&scan_bytes) {
        if let (Some(dim), Some(base64_raw)) = (caps.get(1), caps.get(3)) {
            let dim_str = String::from_utf8_lossy(dim.as_bytes());
            let raw_str = String::from_utf8_lossy(base64_raw.as_bytes());
            let base64_clean: String = raw_str.lines()
                .map(|l| l.trim_start_matches(';').trim())
                .collect();
            
            if let Ok(png_bytes) = base64::engine::general_purpose::STANDARD.decode(base64_clean) {
                if let Some(home) = dirs::home_dir() {
                    let thumb_dir = home.join(".config/rmr/thumbnails");
                    let _ = std::fs::create_dir_all(&thumb_dir);
                    let file_stem = path.file_stem().and_then(|s| s.to_str()).unwrap_or("thumb");
                    let thumb_file_name = format!("{}_{}.png", file_stem, dim_str);
                    let full_thumb_path = thumb_dir.join(&thumb_file_name);
                    if std::fs::write(&full_thumb_path, png_bytes).is_ok() {
                        thumbnail_path = Some(full_thumb_path.to_string_lossy().to_string());
                    }
                }
            }
        }
    }

    Ok(GCodeMetadata {
        estimated_time,
        layer_height,
        slicer_type,
        thumbnail_path,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    #[test]
    fn test_gcode_analysis() {
        let temp_dir = std::env::temp_dir();
        let file_path = temp_dir.join("test_print.gcode");

        // Write a mock G-code file with slicer comments
        let mut file = File::create(&file_path).unwrap();
        writeln!(file, "; G-code generated by PrusaSlicer").unwrap();
        writeln!(file, "; generator = PrusaSlicer 2.7.1").unwrap();
        writeln!(file, "; layer_height = 0.15").unwrap();
        writeln!(file, "; estimated printing time (normal mode) = 1h 45m 30s").unwrap();
        writeln!(file, "; thumbnail begin 16x16 100").unwrap();
        writeln!(file, "; iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAAI0lEQVQ4y2NgGAWjYBSMAlrBqIGhAgxDCQAyDEXwBwADAAD//wM9ADF/268+AAAAAElFTkSuQmCC").unwrap();
        writeln!(file, "; thumbnail end").unwrap();
        writeln!(file, "G1 X10 Y10 Z0.15 E1.0").unwrap();
        writeln!(file, "M104 S0").unwrap();
        drop(file);

        let meta = analyze_gcode(&file_path).unwrap();
        
        assert_eq!(meta.slicer_type, Some("PrusaSlicer 2.7.1".to_string()));
        assert_eq!(meta.layer_height, Some(0.15));
        assert_eq!(meta.estimated_time, Some(3600.0 + 45.0 * 60.0 + 30.0));
        assert!(meta.thumbnail_path.is_some());
        
        // Check that png file exists
        let thumb_p = meta.thumbnail_path.unwrap();
        assert!(Path::new(&thumb_p).exists());

        // Cleanup
        let _ = std::fs::remove_file(&file_path);
        let _ = std::fs::remove_file(&thumb_p);
    }
}
